Aticle page
CollinsTatang/html-project1 pull request #4
Opened 2021-01-15 07:56 UTC by CollinsTatang

Intensive work is done on this project. 
Waiting for your respond

2021-01-15 08:11 UTC, peterrobert requested changes
### ### INVALID 🛑 
Hello, @CollinsTatang nice progress. You have done such an impressive job 👍🏿 . However, it seems you forgot to add a readme to your project. Remember for your project to be reviewed it needs to meet all the minimum requirements. 

[Here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/) is a link to the minimum requirements that must be met.

No worries just add a readme file and submit your project for another review. 

Note: I also noticed that you have some unresolved linter issues. Kindly resolve this too.

**if you have any question, kindly reached me on slack** @peterrobert

### HAPPY CODING 💻

2021-01-15 08:50 UTC, arslanbisharat requested changes
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**

- [x] **Descriptive PR**

1.	Add more descriptive information to your PR message. Please tell something interesting to the TSEs and what you liked about the project. 
2.	The bullet points are nice to add.

- [x] **Descripive Readme**
Please add a proper description in your Readme. [Here](https://github.com/arslanbisharat/New-York-Times-Page/blob/master/README.md) is an example. 

- [x] You have a number of linter errors. Please work on it. Always check if you have any errors before requiring a code review. 
- [x] Don't use IDs in selectors.
- [x] You are missing the bottom section(Suggested newsletters for you, Most Popular, Editors’ Picks) of the original webpage. Please add those sections. 
- [x] Everything in the navbar is actually clickable it's mean those are links somehow. Please work on it. 
<img width="941" alt="1" src="https://user-images.githubusercontent.com/58504655/104702634-178f8980-5738-11eb-933b-ff56924ae911.PNG">

- [ ]  Editors’ Picks section is missing on your webpage. Please add that section. 
<img width="182" alt="2" src="https://user-images.githubusercontent.com/58504655/104702699-32fa9480-5738-11eb-83ec-ef8e05299285.PNG">

- [ ] I can see your work with your partner on this project but you submitted this project individually. You should not click "I worked alone on this project" if the project is collaborative. For the next submission please avoid repeating it. 


**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach me out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2021-01-15 14:55 UTC, Georjane requested changes
## Status: Changes Required 🔧
### Hi There Team✋🏽
 
- [x] Nice work, your ReadMe file looks good but it can look even better. Using the example of the proposed standard by Microverse for the Readme in the last review you got, you can improve your readme file and make it professional by simply forking this [Readme Template](https://github.com/microverseinc/readme-template):

that way, you can add an author's section for example that will look like this:
![author1](https://user-images.githubusercontent.com/60772732/104741637-c2f50a00-5749-11eb-8d0d-9eb93c5820d0.png)
which looks more presentable.

- [x] Also please fix all linter errors too and then submit for another pull request.
- [ ] Your pull request description can be better too

Feel free to reach out to me on slack if you have any questions, Witah Georjane 🤝

Good luck on your project and Happy Coding 💻

2021-01-15 23:21 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Lets fix linter issues
- [ ] Lets align the editors pick a little to the left
![1](https://user-images.githubusercontent.com/23278161/104787781-c3fd5a00-5790-11eb-8551-cf366ceadd6f.png)

- [ ] Lets write a concise readme.MD file that contains project title, description and technologies used
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2021-01-18 13:52 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello guys**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] The project must have a descriptive README.md ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png)from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).
- [ ] Please make sure to fix all of your linters errors.
- [ ] most of your images are not in tteh repo, please make sure to add them and fix all of the broken links.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-01-20 00:22 UTC, arslanbisharat requested changes
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**

- [ ] As requested by every TSEs, Please remove linter errors before requesting Code Review. 
<img width="753" alt="1" src="https://user-images.githubusercontent.com/58504655/105109476-6d6c8480-5ade-11eb-93d7-311a436e6b45.PNG">

- [ ] As requested by every TSEs, Please add proper instructions in your Readme file.[This ](https://github.com/tta2yta/The-New-York-Times-WebSite/blob/feature/README.md)is how it should look like. 
- [ ] ⦁	Descriptive PR
1.	Add more descriptive information to your PR message. Please tell something interesting to the TSEs and what you liked about the project. 
2.	The bullet points are nice to add.

- [ ] These must be links in your Clone: 
1- Everything in the navbar (Buttons, hamburger, and search icon should be clickable while LOGO and SPACE & COSMOS should be links). 
2- LOGO in the Footer section. 
3- Ever item in the footer

- [ ] You are missing the most important sections of the webpage (Editor's pick on the side and More in Space and Astronomy and other associated sections). 
- [ ] Buttons in the navbar should have the same color as present on the original page. 


**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach me out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2021-01-20 16:29 UTC, ntzwilly commented
Starting to make required changes

2021-01-20 19:38 UTC, ntzwilly commented
Pull request description:

1. Add README.md file using Microverse's template
2. Remove Linter errors
3. Add the bottom section(Suggested newsletters for you, Most Popular, Editors’ Picks) of the original webpage.

2021-01-20 20:02 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] 3 simple changes, check below :point_down:

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-20 20:02 UTC, Spayco commented on index.html
> +      <img id="logo" src="images/nyt.png" alt="header image" />
- [ ] Logo should be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

2021-01-20 20:02 UTC, Spayco commented on index.html
> +        </div>
- [ ] you should use an  [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section on the righmost side. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))

2021-01-21 08:23 UTC, ntzwilly commented on README.md
> +
A valid link to the GitHub Pages site is added to the README.md

2021-01-21 08:24 UTC, ntzwilly commented on index.html
> +      <img id="logo" src="images/nyt.png" alt="header image" />
The logo is now a link

2021-01-21 08:25 UTC, ntzwilly commented on index.html
> +        </div>
Editor's picks section on the rightmost side use now semantic tag <aside> instead of <div>

2021-01-21 08:31 UTC, ntzwilly commented
Pull request description:
1. README.md has a valid link to the live demo of the project.
2. The logo on the header section is now a link.
3. Semantic tag <aside> is used for editor's picks instead of div.

2021-01-21 08:35 UTC, arslanbisharat approved these changes
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project and I am very happy to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:


_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2021-02-26 07:58 UTC, closed without merging